### ISSUE TITLE
Some sudden bugs about the website

### ISSUE THREAD

**Issue by HESYlaowang** [Lxns-Network/maimai-prober-frontend#2]
Cannot open login page.
TypeError: Failed to fetch dynamically imported module: https://maimai.lxns.net/assets/9bd8d006.js

When turning to name plate, there's another error.
TypeError: Cannot read properties of undefined (reading 'length')
    at https://maimai.lxns.net/assets/283ce79a.js:1:4427
    at Array.forEach (<anonymous>)
    at https://maimai.lxns.net/assets/283ce79a.js:1:4362
    at Array.forEach (<anonymous>)
    at m (https://maimai.lxns.net/assets/283ce79a.js:1:4342)
    at De (https://maimai.lxns.net/assets/283ce79a.js:1:4505)
    at mo (https://maimai.lxns.net/assets/2596920d.js:30:16958)
    at Qa (https://maimai.lxns.net/assets/2596920d.js:32:43691)
    at Ba (https://maimai.lxns.net/assets/2596920d.js:32:39496)
    at od (https://maimai.lxns.net/assets/2596920d.js:32:39427)

I tested these in US, check it out if it's ok in China

**Comment by JoinChang** [comment]
第一个问题为前端发版更新导致的，你可以尝试使用 Shift+F5 (Ctrl+F5) 刷新页面的缓存。第二个问题需要补充更多信息，比如是在进行什么操作导致的问题。

**Comment by HESYlaowang** [comment]
第二个那个查询極将神舞舞牌子会报错

**Comment by HESYlaowang** [comment]
应该也是更新导致的吧

**Comment by HESYlaowang** [comment]
是更新的问题 清缓存后OK了 谢谢

**Comment by JoinChang** [comment]
确认到第二个问题为未登录状态下查询牌子导致的，将于后续修复。
